export const CREATE_RECORD = "CREATE_RECORD";
export const UPDATE_DATA = "UPDATE_DATA";
export const GET_ALL_DATA = "GET_ALL_DATA";
export const DATA_FAILURE = "DATA_FAILURE";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const ERROR = "ERROR";

/*

CREATE
RETRIEVE_DATA
UPDATE_DATA
DELETE_DATA
ERROR
SEARCH
*/
